--Step 1: Database Exploration 
--Explore all objects in the database 
SELECT*
FROM INFORMATION_SCHEMA.TABLES


--Explore all columns in the database 
SELECT*
FROM INFORMATION_SCHEMA.columns 
WHERE table_name = 'dim_products'

--Step 2: Dimensions exploration 
-- Explore all countries our customers came from 
SELECT DISTINCT country 
FROM dbo.[gold.dim_customers]

-- Explore all product and subcategories (Major divisions). 
SELECT DISTINCT category, subcategory, product_name 
FROM dbo.[gold.dim_products]
ORDER BY 1,2,3 

--Step 3: Date exploration 
--Find the date of the first and last order
--How many years of sales are available 
SELECT 
	MIN(order_date) AS first_order_date,
	MAX(order_date) AS last_order_date,
	DATEDIFF(Year,MIN (order_date), MAX(order_date)) AS order_range_years
FROM [gold.fact_sales]

--Find the youngest and oldest customers and their age
SELECT
	MIN(birthdate) AS oldest_customer,
	DATEDIFF(Year,MIN(birthdate), GETDATE()) oldest_age,
	MAX(birthdate) AS youngest_customer, 
	DATEDIFF(Year,MAX(birthdate), GETDATE()) youngest_age
FROM dbo.[gold.dim_customers]


--Step 4: Measures exploration 
--Find the total sales

SELECT SUM(sales_amount) AS total_sales
FROM dbo.[gold.fact_sales]

--How many items are sold
SELECT SUM(quantity) AS total_items_sold
FROM dbo.[gold.fact_sales]

--Find the average selling price

SELECT AVG(price) AS average_price
FROM dbo.[gold.fact_sales]

--Find the total number of orders 

SELECT COUNT(DISTINCT order_number) AS total_orders
FROM dbo.[gold.fact_sales]

--Find the total number of products

SELECT COUNT(DISTINCT product_key) AS total_products
FROM dbo.[gold.dim_products]


--Find the total number of customers

SELECT COUNT(DISTINCT customer_number) AS total_customers
FROM dbo.[gold.dim_customers]

--Find the total number of customers that have placed an order

SELECT COUNT (DISTINCT customer_key) AS customers_placed_order
FROM dbo.[gold.fact_sales]

--Generate report that shows all key metrics of our business

SELECT 'Total Sales' AS measure_name,  SUM(sales_amount) AS measure_value FROM dbo.[gold.fact_sales]
UNION ALL
SELECT 'Total Quantity' AS measure_name, SUM(quantity) AS measure_value FROM dbo.[gold.fact_sales]
UNION ALL
SELECT 'Average price' AS measure_name,  AVG(price) AS measure_value FROM dbo.[gold.fact_sales]
UNION ALL
SELECT 'Total Nr. of orders' as measure_name, COUNT(DISTINCT order_number) meausure_value FROM dbo.[gold.fact_sales]
UNION ALL
SELECT 'Total Nr. of Products' AS measure_name, COUNT(DISTINCT product_key) AS measure_value FROM dbo.[gold.dim_products]
UNION ALL 
SELECT 'Total Nr. of Customers' AS measure_name, COUNT(DISTINCT customer_number) AS measure_value FROM dbo.[gold.dim_customers]


--Step 5: Magnitude Analysis 
--Find the total number of customers by country

SELECT
	country, 
	COUNT (customer_id) AS total_customers
FROM dbo.[gold.dim_customers]
GROUP BY country 
ORDER BY total_customers DESC

--Find the total number of customers by gender

SELECT
	gender,
	COUNT (customer_id) AS total_customers
FROM dbo.[gold.dim_customers]
GROUP BY gender
ORDER BY total_customers DESC

--Find total products by category

SELECT
	category,
	COUNT(product_key) AS total_products
FROM dbo.[gold.dim_products]
GROUP BY category
ORDER BY total_products DESC

--What is the average costs of each category

SELECT
	category,
	AVG(cost) AS average_cost
FROM dbo.[gold.dim_products]
GROUP BY category
ORDER BY average_cost DESC

--Find total revenue generated by each category

SELECT
p.category,
SUM (f.sales_amount) AS total_revenue
FROM dbo.[gold.fact_sales] f
LEFT JOIN dbo.[gold.dim_products] p
ON f.product_key = p.product_key
GROUP BY p.category 
ORDER BY total_revenue DESC

--Find total revenue generated by each customer

SELECT
c.customer_key,
c.first_name,
c.last_name,
SUM(f.sales_amount) AS total_revenue 
FROM dbo.[gold.dim_customers] c
LEFT JOIN dbo.[gold.fact_sales] f
ON c.customer_key = f.customer_key
GROUP BY
c.customer_key,
c.first_name,
c.last_name
ORDER BY total_revenue DESC

--What is the distribution of sold items across countries 


SELECT
c.country,
SUM(f.quantity) AS total_sold_items
FROM dbo.[gold.dim_customers] c
LEFT JOIN dbo.[gold.fact_sales] f
ON c.customer_key = f.customer_key
GROUP BY
c.country
ORDER BY total_sold_items DESC

--STEP 6: Ranking Analysis
--Which 5 products generate the highest revenue 


SELECT TOP 5
p.product_name,
SUM(s.sales_amount) AS total_revenue
FROM dbo.[gold.fact_sales] s
LEFT JOIN dbo.[gold.dim_products] p
ON s.product_key = p.product_key
GROUP BY p.product_name
ORDER BY total_revenue DESC


--What are the worst perfoming products in terms of sales

SELECT TOP 5
p.product_name,
SUM(s.sales_amount) AS total_revenue
FROM dbo.[gold.fact_sales] s
LEFT JOIN dbo.[gold.dim_products] p
ON s.product_key = p.product_key
GROUP BY p.product_name
ORDER BY total_revenue

--TOP 3 customers with the fewest orders placed

SELECT TOP 3
c.customer_key,
c.first_name,
c.last_name,
COUNT(DISTINCT order_number) AS order_number
FROM dbo.[gold.dim_customers] c
LEFT JOIN dbo.[gold.fact_sales] f
ON c.customer_key = f.customer_key
GROUP BY
c.customer_key,
c.first_name,
c.last_name
ORDER BY order_number 



--Step 7: Change_over-time analysis
--Analyze sales perfomance over years and number of customers

SELECT
Year(order_date) AS order_year
,SUM(sales_amount) AS total_sales
,COUNT(DISTINCT customer_key) AS total_customers
,SUM(quantity) AS total_quantity
FROM dbo.[gold.fact_sales]
WHERE order_date IS NOT NULL
GROUP BY Year(order_date) 
ORDER BY Year(order_date)

--Analyze sales perfomance over months 

SELECT
Month(order_date) AS order_year
,SUM(sales_amount) AS total_sales
,COUNT(DISTINCT customer_key) AS total_customers
,SUM(quantity) AS total_quantity
FROM dbo.[gold.fact_sales]
WHERE order_date IS NOT NULL
GROUP BY Month(order_date) 
ORDER BY Month(order_date)

--Analyze sales perfomance over years and over months 

SELECT
Year(order_date) AS order_year
,Month(order_date) AS order_month
,SUM(sales_amount) AS total_sales
,COUNT(DISTINCT customer_key) AS total_customers
,SUM(quantity) AS total_quantity
FROM dbo.[gold.fact_sales]
WHERE order_date IS NOT NULL
GROUP BY Year(order_date), Month(order_date) 
ORDER BY Year(order_date), Month(order_date)

--OR

SELECT
DATETRUNC(month, order_date) AS order_date
,SUM(sales_amount) AS total_sales
,COUNT(DISTINCT customer_key) AS total_customers
,SUM(quantity) AS total_quantity
FROM dbo.[gold.fact_sales]
WHERE order_date IS NOT NULL
GROUP BY DATETRUNC(month, order_date) 
ORDER BY DATETRUNC(month, order_date)


--STEP 8: Cumulative analysis
--calculate the total sales per month and the running totals of sales over time

SELECT
order_date,
total_sales,
SUM(total_sales)OVER (PARTITION BY order_date ORDER BY order_date) AS running_total_sales 
FROM 
(
SELECT
DATETRUNC(month, order_date) AS order_date,
SUM(sales_amount) AS total_sales
FROM dbo.[gold.fact_sales]
WHERE order_date IS NOT NULL
GROUP BY DATETRUNC(month, order_date)
)t; 

--calculate the total sales over years and the running totals of sales over time

SELECT
order_date,
total_sales,
SUM(total_sales)OVER (ORDER BY order_date) AS running_total_sales 
FROM 
(
SELECT
DATETRUNC(year, order_date) AS order_date,
SUM(sales_amount) AS total_sales
FROM dbo.[gold.fact_sales]
WHERE order_date IS NOT NULL
GROUP BY DATETRUNC(year, order_date)
)t; 

Step 9: Perfomance analysis 
-- analyze the yearly perfomance of products by comparing each product's sales to both
--its average sales perfomance and the previous year's sales 

WITH yearly_product_sales AS (
    SELECT
        YEAR(f.order_date) AS order_year,
        p.product_name,
        SUM(f.sales_amount) AS current_sales
    FROM dbo.[gold.fact_sales] f
    LEFT JOIN dbo.[gold.dim_products] p
        ON f.product_key = p.product_key
    WHERE f.order_date IS NOT NULL
    GROUP BY YEAR(f.order_date), p.product_name
)
SELECT
    order_year,
    product_name,
    current_sales,
    AVG(current_sales) OVER (PARTITION BY product_name) AS avg_sales,
    current_sales - AVG(current_sales) OVER (PARTITION BY product_name) AS diff_sales,
    CASE 
        WHEN current_sales - AVG(current_sales) OVER (PARTITION BY product_name) > 0 THEN 'Above Avg'
        WHEN current_sales - AVG(current_sales) OVER (PARTITION BY product_name) < 0 THEN 'Below Avg'
        ELSE 'Avg'
    END AS avg_change,
    LAG(current_sales) OVER (PARTITION BY product_name ORDER BY order_year) AS prev_year_sales,
    current_sales - LAG(current_sales) OVER (PARTITION BY product_name ORDER BY order_year) AS diff_prev_year,
    CASE 
        WHEN current_sales - LAG(current_sales) OVER (PARTITION BY product_name ORDER BY order_year) > 0 THEN 'Increase'
        WHEN current_sales - LAG(current_sales) OVER (PARTITION BY product_name ORDER BY order_year) < 0 THEN 'Decrease'
        ELSE 'No Change'
    END AS prev_year_change
FROM yearly_product_sales
ORDER BY product_name, order_year;

Step 10: Part_to_whole analysis 
--which categories contribute to the most overall sales


WITH category_sales AS(
	SELECT
	category,
	SUM(sales_amount) AS total_sales 
	FROM dbo.[gold.fact_sales] f
	LEFT JOIN dbo.[gold.dim_products] p
	ON p.product_key = f.product_key
	GROUP BY category
)
SELECT
	category,
	total_sales,
	SUM(total_sales) OVER() overall_sales,
	CONCAT (ROUND((CAST(total_sales AS FLOAT) / SUM(total_sales) OVER()) * 100, 2), '%') AS percentage_of_total
FROM category_sales
ORDER BY total_sales DESC

--Step 11: Data Segmentation 
--Segment product into cost ranges and count how many products fall into each segments 
 
WITH product_category AS (
	SELECT
	product_key, 
	product_name,
	cost,
	CASE WHEN cost < 100 THEN 'Below 100'
		 WHEN cost BETWEEN 100 AND 500 THEN '100-500'
		 WHEN cost BETWEEN 500 AND 1000 THEN '500-1000'
		 ELSE 'Above 1000'
	END AS cost_range 
	FROM dbo.[gold.dim_products]
)
SELECT
cost_range,
COUNT (product_key) AS total_products
FROM product_category
GROUP BY cost_range
ORDER BY total_products DESC

--Group customers into 3 segments based on their spending behavior:
--VIP: at least 12 months of history and spending more than $5,000.
--Regular: at least 12 months of histiry but spending $5,000 or less.
--New: lifespan less than 12 months
-- and find the total number of customers by each group 

WITH customer_spending AS (
SELECT
	c.customer_key,
	SUM(f.sales_amount) AS total_spending, 
	MIN(order_date) AS first_order,
	MAX(order_date) AS last_order,
	DATEDIFF(month,MIN(order_date),MAX(order_date)) AS lifespan  
FROM dbo.[gold.fact_sales] f
LEFT JOIN dbo.[gold.dim_customers] c
ON f.customer_key = c.customer_key
GROUP BY c.customer_key
)
SELECT
customer_segment,
COUNT(customer_key) AS total_customers
FROM(
SELECT
customer_key, 
total_spending,
lifespan,
CASE WHEN lifespan >= 12 and total_spending >5000 THEN 'VIP'
	 WHEN lifespan >= 12 and total_spending <=5000 THEN 'Regular'
	 ELSE 'New'
END customer_segment
FROM customer_spending
)t
GROUP BY customer_segment
ORDER BY total_customers DESC


--STEP 12: Build customer report

/*
==========================================================================================
Customer report
===========================================================================================
Purpose: 
This report consolidates key customer metrics and behaviors
Highlights:
	1.Gather essential fields like names, ages, and transaction details.
	2.Segment customers into categories (VIP, Regular, New) and age groups. 
	3.Aggregates customer-level metrics:
		-total_orders
		-total_sales
		-total quantity purchased
		-total products
		-lifespan (in months)
	4.Calculate valuable KPIs:
		-recency (months since last order)
		-average order value
		-average monthly spend 
=========================================================================================
*/

CREATE VIEW report_customers AS
WITH base_query AS (
/*==================================================================================
Step 1: Base Query: Retrieve core columns from tables
==================================================================================*/
SELECT
	f.order_number,
	f.product_key,
	f.order_date,
	f.sales_amount,
	f.quantity,
	c.customer_key,
	c.customer_number, 
	CONCAT(c.first_name, ' ', c.last_name) AS customer_name,
	DATEDIFF(year, c.birthdate, GETDATE()) AS age
FROM dbo.[gold.fact_sales] f
LEFT JOIN dbo.[gold.dim_customers] c
ON f.customer_key = c.customer_key
WHERE order_date IS NOT NULL 
)
,customer_aggregation AS(
/*==================================================================================
Step 2: Customer aggregations: summarizes key metrics at the customer level 
==================================================================================*/
SELECT
	customer_key,
	customer_number,
	customer_name,
	age,
	COUNT(DISTINCT order_number) AS total_orders,
	SUM(sales_amount) AS total_sales,
	SUM(quantity) AS total_quantity,
	COUNT(DISTINCT product_key) AS total_products,
	MAX(order_date) AS last_order_date,
	DATEDIFF(month, MIN(order_date), MAX(order_date)) AS lifespan  
FROM base_query
GROUP BY
	customer_key,
	customer_number,
	customer_name,
	age
)
SELECT
	customer_key,
	customer_number,
	customer_name,
	age,
	CASE WHEN age < 20 THEN 'Under 20'
		 WHEN age BETWEEN 20 AND 29 THEN '20-29'
		 WHEN age BETWEEN 30 AND 39 THEN '30-39'
		 WHEN age BETWEEN 40 AND 49 THEN '40-49'
		 ELSE '50 and Above'
	END age_group,
	CASE WHEN lifespan >= 12 and total_sales >5000 THEN 'VIP'
		 WHEN lifespan >= 12 and total_sales <=5000 THEN 'Regular'
		 ELSE 'New'
	END customer_segment,
	last_order_date,
	DATEDIFF(month, last_order_date, GETDATE()) AS recency, 
	total_orders,
	total_sales,
	total_quantity,
	total_products,
	lifespan,
	--compute average order value (AVO)
	CASE WHEN total_sales = 0 THEN 0
	     ELSE total_sales/total_orders
	END AS avg_order_value, 
	--compute average monthly spend
	CASE WHEN lifespan = 0 THEN total_sales
	     ELSE total_sales/lifespan
	END AS avg_monthly_spend
FROM customer_aggregation

SELECT
customer_segment,
COUNT(customer_number) AS total_customers,
SUM(total_sales) AS total_sales
FROM dbo.report_customers
GROUP BY customer_segment
ORDER BY total_customers DESC

--STEP 13: Build product report

/*
==========================================================================================
Product report
===========================================================================================
Purpose: 
This report consolidates key product metrics and behaviors. 
Highlights
	1.Gather essential fields such as product name, category, subcategory, and cost
	2.Segments products by revenue to identify high-performers, mid-range, and low-performers.
	3.Aggregates product-level metrics: 
		-total orders
		-total sales
		-total quantity sold
		-total customers (unique)
		-Lifespan (in months)
	4.Calculates valuable KPIs:
		-recency (months since last sale)
		-average order revenue (AOR)
		-average monthly revenue 
=========================================================================================
*/
CREATE VIEW report_product AS
WITH base_query AS(
/*==================================================================================
Step 1: Base Query: Retrieve core columns from fact_sales and dim_products
==================================================================================*/
	SELECT
		f.order_number,
		f.order_date,
		f.customer_key,
		f.sales_amount,
		f.quantity,
		p.product_key,
		p.product_name,
		p.category,
		p.subcategory,
		p.cost
	FROM dbo.[gold.fact_sales] f
	LEFT JOIN dbo.[gold.dim_products] p
	ON f.product_key = p.product_key
	WHERE order_date IS NOT NULL
	),
	product_aggregations AS(
/*==================================================================================
 Step 2: Product aggregations: summarizes key metrics at the product level 
==================================================================================*/
	SELECT
		product_key,
		product_name,
		category,
		subcategory,
		cost,
		DATEDIFF(month, MIN(order_date), MAX(order_date)) AS lifespan,
		MAX(order_date) AS last_sale_date,
		COUNT(DISTINCT customer_key) AS total_customers,
		COUNT(DISTINCT order_number) AS total_orders,
		SUM(sales_amount) AS total_sales,
		SUM(quantity) AS total_quantity,
		ROUND(AVG(CAST(sales_amount AS FLOAT)/NULLIF(quantity, 0)),1) AS avg_selling_price  
	FROM base_query
	GROUP BY
		product_key,
		product_name,
		category,
		subcategory,
		cost
)
/*==================================================================================
Step 3: combines all product result into one output
==================================================================================*/
SELECT
	product_key,
	product_name,
	category,
	subcategory,
	cost,
	last_sale_date,
	DATEDIFF(month, last_sale_date, GETDATE()) AS recency_in_months,
	CASE
		WHEN total_sales > 50000 THEN 'High_perfomer'
		WHEN total_sales > 10000 THEN 'Mid_range'
		ELSE 'Low_perfomer'
	END AS product_segment,
	lifespan,
	total_customers,
	total_orders,
	total_sales,
	total_quantity,
	avg_selling_price,  
	--calculate average order revenue (AOR)
	CASE
		WHEN total_orders = 0 THEN 0
		ELSE total_sales/total_orders
	END AS avg_order_revenue,
	--calculate average monthly revenue
	CASE 
		WHEN lifespan = 0 THEN total_sales
		ELSE total_sales/lifespan
	END AS avg_monthly_revenue
FROM product_aggregations




